version: '3'

tasks:
  stage:
    desc: 'stage'
    cmds:
      - git add .
    silent: false
  format:
    desc: 'format'
    cmds:
      - nix --extra-experimental-features "nix-command flakes" shell nixpkgs#nixpkgs-fmt -c nixpkgs-fmt  .
      - nix --extra-experimental-features "nix-command flakes" shell nixpkgs#stylua -c stylua  .
    silent: false
  build:
    desc: 'build'
    deps:
      - stage
      - format
    vars:
      PLATFORM:
        sh: uname -s
    cmds:
      - nix --extra-experimental-features "nix-command flakes" build --max-jobs 4 ".#darwinConfigurations.{{.PLATFORM}}.system"
    silent: false
  apply:
    desc: 'apply'
    deps:
      - build
    vars:
      PLATFORM:
        sh: uname -s
    cmds:
      - ./result/sw/bin/darwin-rebuild switch --flake ".#{{.PLATFORM}}"
    silent: false
