version: '3'

tasks:
  format:
    desc: 'format'
    cmds:
      - nixpkgs-fmt .
    silent: false
  build:
    desc: 'build'
    deps:
      - format
    vars:
      LOCAL_HOST_NAME:
        sh: scutil --get LocalHostName
    cmds:
      - nix --extra-experimental-features "nix-command flakes" build --max-jobs 4 ".#darwinConfigurations.{{.LOCAL_HOST_NAME}}.system"
    silent: false
  apply:
    desc: 'apply'
    deps:
      - build
    cmds:
      - bash -c 'git add . && ./result/sw/bin/darwin-rebuild switch --flake ".#{{.LOCAL_HOST_NAME}}"'
    silent: false
  apply-commit:
    desc: 'commited apply'
    deps:
      - build
    cmds:
      - bash -c 'git add . && git commit && ./result/sw/bin/darwin-rebuild switch --flake ".#{{.LOCAL_HOST_NAME}}"'
    silent: false
