version: '3'

tasks:
  stage:
    desc: 'stage'
    cmds:
      - git add .
    silent: false
  format:
    desc: 'format'
    cmds:
      - nixpkgs-fmt .
      - stylua .
    silent: false
  build:
    desc: 'build'
    deps:
      - stage
      - format
    vars:
      LOCAL_HOST_NAME:
        sh: scutil --get LocalHostName
    cmds:
      - nix --extra-experimental-features "nix-command flakes" build --max-jobs 4 ".#darwinConfigurations.{{.LOCAL_HOST_NAME}}.system"
    silent: false
  apply:
    desc: 'apply'
    deps:
      - build
    cmds:
      - ./result/sw/bin/darwin-rebuild switch --flake ".#"
    silent: false
