version: '3'

tasks:
  build:
    desc: 'build'
    vars:
      LOCAL_HOST_NAME:
        sh: scutil --get LocalHostName
    cmds:
      - nix --extra-experimental-features "nix-command flakes" build ".#darwinConfigurations.Air.system"
    silent: false
  apply:
    desc: 'apply'
    deps:
      - build
    cmds:
      - ./result/sw/bin/darwin-rebuild switch --flake ".#Air"
    silent: false
