# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "${ZINIT_HOME}/zinit.zsh"

export LANG=en_US.UTF-8
export EDITOR=nvim
eval "$(direnv hook zsh)"

# asdf terraform とかめんどくさいもののために使えるようにしておく
export ASDF_HASHICORP_OVERWRITE_ARCH=amd64

## asdf completions
fpath=(${ASDF_DIR}/completions $fpath)
# initialise completions with ZSH's compinit
autoload -Uz compinit && compinit

# prompt theming
zinit ice depth=1
zinit light romkatv/powerlevel10k

# prompt syntax highlight
zinit light zsh-users/zsh-syntax-highlighting

# history search
zinit light robobenklein/zdharma-history-search-multi-word

# ls
zinit light zpm-zsh/ls # エイリアスとか
export ZSH_LS_BACKEND=eza
export CLICOLOR=1
export TERM=xterm-256color
export EZA_COLORS="$(vivid generate iceberg-dark)"
_ls_params=(${_ls_params#--hyperlink})

# aliases
alias sed="gsed"
alias realpath="(){ls --no-icons $1(:a)}"
alias loadenv="(){set -a; source $1; set +a;}"
alias vim='echo "vimなんかありませーん, use n instead of vim"'
alias n=nvim
alias vimdiff="nvim -d"
alias ks=k9s
alias k=kubectl
alias kc=kubectx
alias kn=kubens
alias go=richgo

alias ..="cd .."
alias ...="cd ../.."

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# completion
autoload -U compinit && compinit

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z} r:|[-_.]=**'
zstyle ':completion:*:processes' menu yes select=2
zstyle ':completion:*' list-colors "${(s.:.)EZA_COLORS}"
zstyle ':completion:*:default' menu select=1

# C-w でいい感じに削除できるように
export WORDCHARS="*?_-.[]~&;=!#$%^(){}<>"

# Tmux Plugin Manger のインストールは力技使う
if [[ ! -d "${HOME}/.tmux/plugins/tpm" ]]; then
  git clone https://github.com/tmux-plugins/tpm.git "${HOME}/.tmux/plugins/tpm"
fi

# Functions
zd() {
  local dir
  dir=$(find ${1:-.} -path '*/\.*' -prune -o -type d -print 2> /dev/null | fzf +m) &&
  cd "$dir"
}
zgd() {
  local dir
  local workdir
  if [[ $1 ]] then;
      workdir=$1
  else
      workdir=${HOME}/"workspace"
  fi
  dir=$(rg --files --hidden --follow --glob "**/.git/*" $workdir | rev | cut -d '/' -f 3- | rev | sort | uniq | fzf +m) &&
  cd "$dir"
}
