ZSH_CONFIG_HOME="${XDG_CONFIG_HOME}/zsh/rc"

# Basic
source "${ZSH_CONFIG_HOME}/base.rc.zsh"
source "${ZSH_CONFIG_HOME}/alias.rc.zsh"
source "${ZSH_CONFIG_HOME}/color.rc.zsh"
source "${ZSH_CONFIG_HOME}/completions.rc.zsh"

# Plugin Manger
source "${ZSH_CONFIG_HOME}/zinit.rc.zsh"

# tools
source "${ZSH_CONFIG_HOME}/asdf.rc.zsh"
source "${ZSH_CONFIG_HOME}/fzf.rc.zsh"
source "${ZSH_CONFIG_HOME}/p10k.rc.zsh"
source "${ZSH_CONFIG_HOME}/tpm.rc.zsh"

# Functions
source "${ZSH_CONFIG_HOME}/funtions/init.zsh"

# Language Specific
source "${ZSH_CONFIG_HOME}/language-specific/init.zsh"

